name: Package and Upload

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  package:
    env:
      # Set the version of ruby-install to use
      RUBY_INSTALL_VERSION: 0.9.4
      BUILD_PATH: ${{ github.workspace }}/${{ matrix.os }}-${{ matrix.arch }}
      ARCHIVE_PATH: ${{ github.workspace }}/${{ matrix.os }}-${{ matrix.arch }}.tar.gz

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64, arm64]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Install dependencies for Linux
      - name: Install dependencies (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl \
            libssl-dev libreadline-dev zlib1g-dev

      # Install dependencies for macOS
      - name: Install dependencies (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew update
          brew install openssl readline zlib

      # Install ruby-install from source on both OS's
      - name: Install ruby-install from source
        run: |
          curl -LO https://github.com/postmodern/ruby-install/archive/refs/tags/v$RUBY_INSTALL_VERSION.tar.gz
          tar -xzf v$RUBY_INSTALL_VERSION.tar.gz
          cd ruby-install-$RUBY_INSTALL_VERSION

          make
          sudo make install
          ruby-install --version

      # Run your build script. BUILD_PATH and ARCHIVE_PATH are used by this script.
      - name: Run build script
        run: |
          bash builder/build.sh

      - name: Log package architecture
        run: |
          validate() {
            local dir="$1"
            if [[ ! -d "$dir" ]]; then
              echo "Error: '$dir' is not a directory or does not exist." >&2
              return 1
            fi

            find "$dir" -type f | while read -r filepath; do
              filetype=$(file -b "$filepath")
              echo "$filepath [$filetype]"
            done
          }

          uname -m
          uname -s

          validate "$BUILD_PATH/package/vendor/bin"
          validate .

      # Upload the final tar.gz artifact for each OS/arch
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  upload:
    needs: package
    runs-on: ubuntu-latest
    environment: Tigris Terminalwire Client Bucket

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -R artifacts/

      # Upload to S3-compatible bucket
      - name: Upload artifacts to Tigris
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_ENDPOINT_URL_S3: ${{ vars.AWS_ENDPOINT_URL_S3 }}
          AWS_ENDPOINT_URL_IAM: ${{ vars.AWS_ENDPOINT_URL_IAM }}
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          # Use the GitHub Actions run ID as the build ID
          BUILD_ID=${{ github.run_id }}
          TARGET_DIR="builds/$BUILD_ID"

          # Upload each artifact to Tigris
          find artifacts -type f | while read file; do
            BASENAME=$(basename "$file")
            echo "Uploading $BASENAME to S3 bucket $S3_BUCKET_NAME"
            aws s3 cp "$file" "s3://$S3_BUCKET_NAME/$TARGET_DIR/$BASENAME" --acl public-read
          done
