name: Release

on:
  workflow_run:
    workflows: ["Package"]
    types:
      - completed

jobs:
  upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          # Downloads all artifacts uploaded by the upstream workflow
          path: artifacts/

      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -R artifacts/

      - name: Upload artifacts to S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          # Use the GitHub Actions run ID as the build ID
          BUILD_ID=${{ github.event.workflow_run.id }}
          TARGET_DIR="builds/$BUILD_ID"

          # Ensure the artifacts directory exists
          if [ ! -d "artifacts" ]; then
            echo "No artifacts found to upload."
            exit 1
          fi

          # Upload all artifacts to S3
          find artifacts -type f | while read file; do
            echo "Uploading $file to s3://$S3_BUCKET_NAME/$TARGET_DIR/$(basename $file)"
            aws s3 cp "$file" "s3://$S3_BUCKET_NAME/$TARGET_DIR/$(basename $file)" --acl public-read
          done
